# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1edaaa09029e7a5e4febb876e9a6fc6de0e4f26504802701bd57dc66595fe5c3c4848a52c5f57bc6027515e39535051b31a09bde630176375350fb18ff090fae

test:
  secret_key_base: 308e0cd70637e313473b0a4beb5de00d972e598521c4b1cd3d747d1af8c937a7634cca3c1bbc045d6ede1f5b224c147612f40d3d5c4e8174efa4c3b3428d3a21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
